export const PLACEHOLDER_IMAGE_PATH = '/images/placeholder.png';

export const BLUR_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO3Z4xQAAAAASUVORK5CYII=';
